### ISSUE TITLE
Build failed ?? How to build application for production

### ISSUE THREAD

**Issue by GopinathKaliappan** [cornflourblue/react-redux-registration-login-example#13]
I was trying to make build but i dont know how to do that

**Comment by ashishguptaevontech** [comment]
Any update on above?

**Comment by chiragpurohit71085** [comment]
Hi anybody is able to make build?

**Comment by cornflourblue** [comment]
I've just added a production build script to the package.json so you can run `npm run build` to build the app into the `/dist` directory

Cheers,
Jason

**Comment by chiragpurohit71085** [comment]
Thanks
