### ISSUE TITLE
Dispatch is not a function 

### ISSUE THREAD

**Issue by sanjeetiitr** [cornflourblue/react-redux-registration-login-example#7]
I am getting this error  " Dispatch is not a function "  every time when I run it. 

This is the section of code from login Page where i am getting this error.
```
   handleSubmit(e){
        e.preventDefault();
        console.log(JSON.stringify(this.state));
        this.setState({ submitted : true });
        const { username, password } = this.state;
        // console.log(username);
        // console.log(password);
        const { dispatch } = this.props;
        if ( username && password) {
            console.log('sasjas');
            dispatch(userActions.login(username,password)); //  Dispatch is not a function
        }
    }
```

**Comment by emilyparkes** [comment]
Hi there @sanjeetiitr,
Did you install  and have `"redux-thunk": "^2.2.0"` in your package.json?
And are you using it in your `client/index.js` like so:
```
... other imports
import {createStore, applyMiddleware, compose} from 'redux'
import thunkMiddleware from 'redux-thunk'

import reducers from './reducers'
import App from './components/App'
let store = createStore(reducers, compose(
  applyMiddleware(thunkMiddleware),
  window.devToolsExtension ? window.devToolsExtension() : f => f
))

... <App />
```

**Comment by john-raymon** [comment]
This is late, but are you sure you mapped the dispatch to props ? or maybe what @emilyparkes mentioned ?

**Comment by cornflourblue** [comment]
This can happen if your component uses `mapDispatchToProps`, which stops `dispatch` from being injected into your component, there's more information available at https://react-redux.js.org/using-react-redux/connect-mapdispatch#why-is-my-component-not-receiving-dispatch
